2018/10/09 10:27:18 [emerg] 13356#0: mkdir() "/home/dl/workspace/eotu_nginx/debug/nginx/client_body_temp" failed (13: Permission denied)
2018/10/09 10:28:27 [emerg] 13424#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/10/09 10:28:27 [emerg] 13424#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/10/09 10:28:27 [emerg] 13424#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/10/09 10:28:27 [emerg] 13424#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/10/09 10:28:27 [emerg] 13424#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/10/09 10:28:27 [emerg] 13424#0: still could not bind()
2018/10/09 10:29:29 [emerg] 13466#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/10/09 10:29:29 [emerg] 13466#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/10/09 10:29:29 [emerg] 13466#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/10/09 10:37:52 [emerg] 14171#0: open() "/home/dl/workspace/eotu_nginx/debug/nginx/logs/access.log" failed (13: Permission denied)
2018/10/09 10:38:00 [emerg] 14176#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/10/09 10:38:00 [emerg] 14176#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/10/09 10:38:00 [emerg] 14176#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/10/09 10:38:00 [emerg] 14176#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/10/09 10:42:21 [emerg] 14575#0: open() "/home/dl/workspace/eotu_nginx/debug/nginx/logs/access.log" failed (13: Permission denied)
2018/10/09 10:43:41 [emerg] 14742#0: unknown directive "echo" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:49
2018/10/09 10:57:46 [emerg] 23751#0: "set" directive is not allowed here in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:36
2018/10/09 10:57:59 [emerg] 23772#0: "set" directive is not allowed here in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:36
2018/10/09 10:58:50 [emerg] 23813#0: "set" directive is not allowed here in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:36
2018/10/09 10:59:16 [emerg] 23882#0: "lua_package_path" directive is not allowed here in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:47
2018/10/09 10:59:41 [emerg] 23905#0: "lua_package_path" directive is not allowed here in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:47
2018/10/09 11:00:47 [emerg] 23979#0: "set" directive is not allowed here in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:35
2018/10/09 11:03:39 [emerg] 24219#0: unknown "lua_file_root_path123" variable
2018/10/09 11:03:54 [emerg] 24241#0: invalid variable name in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:56
2018/10/09 11:05:43 [emerg] 24358#0: unexpected "}" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:58
2018/10/09 11:05:49 [emerg] 24371#0: unknown directive "ngx.say(ngx.var.arg_a)" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:57
2018/10/09 11:20:01 [error] 24917#0: *1 failed to load inlined Lua code: content_by_lua(nginx.conf:83):8: unexpected symbol near '#', client: 127.0.0.1, server: localhost, request: "GET /request_body HTTP/1.1", host: "localhost"
2018/10/09 11:20:17 [error] 24917#0: *2 failed to load inlined Lua code: content_by_lua(nginx.conf:83):8: unexpected symbol near '#', client: 127.0.0.1, server: localhost, request: "POST /request_body HTTP/1.1", host: "localhost"
2018/10/09 11:21:00 [error] 25002#0: *1 failed to load inlined Lua code: content_by_lua(nginx.conf:83):4: unexpected symbol near '#', client: 127.0.0.1, server: localhost, request: "POST /request_body HTTP/1.1", host: "localhost"
2018/10/09 11:33:59 [error] 25424#0: *1 failed to load external Lua file "/home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua": cannot open /home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua: No such file or directory, client: 127.0.0.1, server: localhost, request: "GET /api/addition?a=1 HTTP/1.1", host: "127.0.0.1"
2018/10/09 11:35:05 [error] 25497#0: *1 failed to load external Lua file "/home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua": cannot open /home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua: No such file or directory, client: 127.0.0.1, server: localhost, request: "GET /api/addition?a=1 HTTP/1.1", host: "127.0.0.1"
2018/10/09 11:35:14 [error] 25497#0: *2 failed to load external Lua file "/home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua": cannot open /home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua: No such file or directory, client: 127.0.0.1, server: localhost, request: "GET /api/addition?a=1 HTTP/1.1", host: "localhost"
2018/10/09 11:35:20 [error] 25497#0: *3 failed to load external Lua file "/home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua": cannot open /home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua: No such file or directory, client: 127.0.0.1, server: localhost, request: "GET /api/addition?a=1 HTTP/1.1", host: "localhost"
2018/10/09 11:35:27 [error] 25497#0: *4 failed to load external Lua file "/home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua": cannot open /home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua: No such file or directory, client: 127.0.0.1, server: localhost, request: "GET /api/addition?a=1 HTTP/1.1", host: "localhost"
2018/10/09 11:36:18 [error] 25497#0: *7 failed to load external Lua file "/home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua": cannot open /home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua: No such file or directory, client: 127.0.0.1, server: localhost, request: "GET /api/addition?a=1 HTTP/1.1", host: "localhost"
2018/10/09 11:36:21 [error] 25497#0: *8 failed to load external Lua file "/home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua": cannot open /home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua: No such file or directory, client: 127.0.0.1, server: localhost, request: "GET /api/addition?a=1 HTTP/1.1", host: "localhost"
2018/10/09 11:36:38 [error] 25497#0: *9 failed to load external Lua file "/home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua": cannot open /home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua: No such file or directory, client: 127.0.0.1, server: localhost, request: "GET /api/addition?a=1 HTTP/1.1", host: "localhost"
2018/10/09 11:36:43 [error] 25625#0: *1 failed to load external Lua file "/home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua": cannot open /home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua: No such file or directory, client: 127.0.0.1, server: localhost, request: "GET /api/addition?a=1 HTTP/1.1", host: "localhost"
2018/10/09 11:37:06 [error] 25682#0: *1 failed to load external Lua file "/home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua": cannot open /home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua: No such file or directory, client: 127.0.0.1, server: localhost, request: "GET /api/addition?a=1 HTTP/1.1", host: "localhost"
2018/10/09 11:45:02 [emerg] 26130#0: invalid number of arguments in "return" directive in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:72
2018/10/09 11:45:09 [emerg] 26145#0: invalid return code "content_by_lua_file" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:73
2018/10/09 11:45:25 [emerg] 26183#0: unexpected "}" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:74
2018/10/09 11:46:18 [emerg] 26237#0: unknown "0" variable
2018/10/09 11:52:35 [error] 26511#0: *1 lua entry thread aborted: runtime error: ...dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua:4: bad argument #1 to 'print' (non-array table found)
stack traceback:
coroutine 0:
	[C]: in function 'print'
	...dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua:4: in function <...dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua:1>, client: 127.0.0.1, server: localhost, request: "GET /api/addition/2/3?a=1&b=3 HTTP/1.1", host: "127.0.0.1"
2018/10/09 11:52:51 [error] 26547#0: *1 lua entry thread aborted: runtime error: ...dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua:4: bad argument #1 to 'print' (non-array table found)
stack traceback:
coroutine 0:
	[C]: in function 'print'
	...dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua:4: in function <...dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua:1>, client: 127.0.0.1, server: localhost, request: "GET /api/addition/2/3?a=1&b=3 HTTP/1.1", host: "127.0.0.1"
2018/10/09 11:56:00 [error] 26724#0: *1 failed to load external Lua file "/home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua": ...dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua:8: 'end' expected (to close 'function' at line 1) near '<eof>', client: 127.0.0.1, server: localhost, request: "GET /api/addition/2/3?a=1&b=3 HTTP/1.1", host: "127.0.0.1"
2018/10/09 11:56:02 [error] 26724#0: *2 failed to load external Lua file "/home/dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua": ...dl/workspace/eotu_nginx/debug/nginx/lua/access_check.lua:8: 'end' expected (to close 'function' at line 1) near '<eof>', client: 127.0.0.1, server: localhost, request: "GET /api/addition/2/3?a=1&b=3 HTTP/1.1", host: "127.0.0.1"
2018/10/09 11:58:11 [error] 26909#0: *1 failed to load external Lua file "/home/dl/workspace/eotu_nginx/debug/nginx/lua/addition/2/3.lua": cannot open /home/dl/workspace/eotu_nginx/debug/nginx/lua/addition/2/3.lua: No such file or directory, client: 127.0.0.1, server: localhost, request: "GET /api/addition/2/3?a=1&b=3 HTTP/1.1", host: "127.0.0.1"
2018/10/09 11:58:25 [error] 26941#0: *1 failed to load external Lua file "/home/dl/workspace/eotu_nginx/debug/nginx/lua/addition/2/3.lua": cannot open /home/dl/workspace/eotu_nginx/debug/nginx/lua/addition/2/3.lua: No such file or directory, client: 127.0.0.1, server: localhost, request: "GET /api/addition/2/3?a=1&b=3 HTTP/1.1", host: "127.0.0.1"
2018/10/09 11:58:45 [error] 26979#0: *1 failed to load external Lua file "/home/dl/workspace/eotu_nginx/debug/nginx/lua/addition/2/3.lua": cannot open /home/dl/workspace/eotu_nginx/debug/nginx/lua/addition/2/3.lua: No such file or directory, client: 127.0.0.1, server: localhost, request: "GET /api/addition/2/3?a=1&b=3 HTTP/1.1", host: "127.0.0.1"
2018/10/09 12:00:32 [error] 27077#0: *1 failed to load external Lua file "/home/dl/workspace/eotu_nginx/debug/nginx/lua/addition/2/3.lua": cannot open /home/dl/workspace/eotu_nginx/debug/nginx/lua/addition/2/3.lua: No such file or directory, client: 127.0.0.1, server: localhost, request: "GET /api/addition/2/3?a=1&b=3 HTTP/1.1", host: "127.0.0.1"
2018/10/09 12:00:34 [error] 27077#0: *2 failed to load external Lua file "/home/dl/workspace/eotu_nginx/debug/nginx/lua/addition/2/3.lua": cannot open /home/dl/workspace/eotu_nginx/debug/nginx/lua/addition/2/3.lua: No such file or directory, client: 127.0.0.1, server: localhost, request: "GET /api/addition/2/3?a=1&b=3 HTTP/1.1", host: "127.0.0.1"
2018/10/09 14:33:49 [emerg] 3591#0: bind() to 0.0.0.0:80 failed (13: Permission denied)
2018/10/09 15:01:07 [error] 3715#0: *1 open() "/home/dl/workspace/eotu_nginx/debug/nginx/html/cgi/reccom" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /cgi/reccom?id=8E84602F4601A4C0B8CC5C520E3E62B754F5878D8208D7A3D429208C482EEC74 HTTP/1.1", host: "tj.b.qq.com"
2018/10/09 15:01:12 [error] 3715#0: *2 open() "/home/dl/workspace/eotu_nginx/debug/nginx/html/search.xml" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /search.xml HTTP/1.1", host: "tj.b.qq.com"
2018/10/09 15:01:44 [error] 3715#0: *3 open() "/home/dl/workspace/eotu_nginx/debug/nginx/html/cgi-bin/pu-cgi" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "POST /cgi-bin/pu-cgi HTTP/1.1", host: "crsignv1.qq.com"
2018/10/09 15:01:52 [error] 3715#0: *4 open() "/home/dl/workspace/eotu_nginx/debug/nginx/html/im/15.png" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /im/15.png HTTP/1.1", host: "qqlogo.qq.com"
2018/10/09 15:01:57 [error] 3715#0: *5 open() "/home/dl/workspace/eotu_nginx/debug/nginx/html/search.xml" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /search.xml HTTP/1.1", host: "tj.b.qq.com"
2018/10/09 15:02:03 [error] 3715#0: *6 open() "/home/dl/workspace/eotu_nginx/debug/nginx/html/god/images/cwci.png" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /god/images/cwci.png HTTP/1.1", host: "s.qun.qq.com"
2018/10/09 15:02:13 [error] 3715#0: *7 open() "/home/dl/workspace/eotu_nginx/debug/nginx/html/god/images/litegame.png" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /god/images/litegame.png HTTP/1.1", host: "s.qun.qq.com"
2018/10/09 15:02:23 [error] 3715#0: *8 open() "/home/dl/workspace/eotu_nginx/debug/nginx/html/god/images/channeltoolicon.png" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /god/images/channeltoolicon.png HTTP/1.1", host: "s.qun.qq.com"
2018/10/09 15:53:35 [emerg] 6827#0: bind() to 0.0.0.0:80 failed (13: Permission denied)
2018/10/09 15:59:43 [error] 7141#0: *1 attempt to receive data on a closed socket: u:0000000000000000, c:0000000000000000, client: 127.0.0.1, server: localhost, request: "GET /udp HTTP/1.1", host: "localhost"
2018/10/09 15:59:58 [error] 7207#0: *1 attempt to receive data on a closed socket: u:0000000000000000, c:0000000000000000, client: 127.0.0.1, server: localhost, request: "GET /udp HTTP/1.1", host: "localhost"
2018/10/09 16:00:00 [error] 7207#0: *2 attempt to receive data on a closed socket: u:0000000000000000, c:0000000000000000, client: 127.0.0.1, server: localhost, request: "GET /udp HTTP/1.1", host: "localhost"
2018/10/09 16:00:07 [error] 7239#0: *1 attempt to receive data on a closed socket: u:0000000000000000, c:0000000000000000, client: 127.0.0.1, server: localhost, request: "GET /udp HTTP/1.1", host: "localhost"
2018/10/09 16:05:17 [emerg] 7464#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:22
2018/10/09 16:05:52 [emerg] 7523#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:07:14 [emerg] 7564#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:10:05 [emerg] 16048#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:10:33 [emerg] 16106#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:13:05 [emerg] 16211#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:13:37 [emerg] 16280#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:13:46 [emerg] 16302#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:14:24 [emerg] 16330#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:15:27 [emerg] 16381#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:15:36 [emerg] 16397#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:16:15 [emerg] 16438#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:17:22 [emerg] 16530#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:18:57 [emerg] 16595#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:19:22 [emerg] 16624#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:19:55 [emerg] 16696#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:20:02 [emerg] 16714#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:20:15 [emerg] 16738#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:23:21 [emerg] 16925#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:25:29 [emerg] 17007#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:28:36 [emerg] 17134#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:28:44 [emerg] 17162#0: invalid parameter "udp" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:51
2018/10/09 16:29:16 [emerg] 17198#0: invalid parameter "udp" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:51
2018/10/09 16:30:25 [emerg] 17296#0: invalid parameter "udp" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:51
2018/10/09 16:30:59 [emerg] 17359#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:34:47 [emerg] 17578#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:37:08 [emerg] 17647#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:37:30 [emerg] 17683#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx//conf/nginx.conf:20
2018/10/09 16:38:29 [emerg] 17751#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:20
2018/10/09 16:39:41 [emerg] 17811#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:20
2018/10/09 16:41:17 [emerg] 17877#0: open() "/home/dl/workspace/eotu_nginx/debug/nginx/./nginx/conf/nginx.conf" failed (2: No such file or directory)
2018/10/09 16:41:35 [emerg] 17886#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:20
2018/10/09 16:41:53 [emerg] 17915#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:20
2018/10/09 16:41:53 [emerg] 17917#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:20
2018/10/09 16:42:31 [emerg] 17946#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:20
2018/10/09 16:42:31 [emerg] 17948#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:20
2018/10/09 16:43:00 [emerg] 17981#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:20
2018/10/09 16:43:10 [emerg] 18005#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:20
2018/10/09 16:43:55 [emerg] 18040#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:20
2018/10/09 16:43:57 [emerg] 18050#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:20
2018/10/09 16:43:57 [emerg] 18052#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:20
2018/10/09 16:44:55 [emerg] 18094#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:20
2018/10/09 16:45:02 [emerg] 18112#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:20
2018/10/09 16:45:44 [emerg] 18142#0: unknown directive "stream" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:20
2018/10/09 16:47:43 [emerg] 22625#0: "echo" directive is not allowed here in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:24
2018/10/09 16:50:58 [emerg] 28142#0: no handler for server in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:21
2018/10/09 16:56:27 [error] 28394#0: *1 open() "/home/dl/workspace/eotu_nginx/debug/nginx/html/udp" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /udp HTTP/1.1", host: "localhost"
2018/10/09 16:58:18 [error] 28592#0: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:26):2: API disabled in the current context
stack traceback:
coroutine 0:
	[C]: in function 'say'
	content_by_lua(nginx.conf:26):2: in function <content_by_lua(nginx.conf:26):1>, udp client: 192.168.1.191, server: 0.0.0.0:8080
2018/10/09 17:00:04 [error] 28592#0: *2 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:26):2: API disabled in the current context
stack traceback:
coroutine 0:
	[C]: in function 'say'
	content_by_lua(nginx.conf:26):2: in function <content_by_lua(nginx.conf:26):1>, udp client: 127.0.0.1, server: 0.0.0.0:8080
2018/10/09 17:02:21 [emerg] 28835#0: "echo" directive is not allowed here in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:27
2018/10/09 17:04:20 [error] 28914#0: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:31):2: attempt to index global 'sock' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:31): in function <content_by_lua(nginx.conf:31):1>, udp client: 127.0.0.1, server: 0.0.0.0:8080
2018/10/09 17:04:37 [error] 28914#0: *2 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:31):2: attempt to index global 'sock' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:31): in function <content_by_lua(nginx.conf:31):1>, udp client: 127.0.0.1, server: 0.0.0.0:8080
2018/10/09 17:05:01 [error] 28914#0: *3 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:31):2: attempt to index global 'sock' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:31): in function <content_by_lua(nginx.conf:31):1>, udp client: 127.0.0.1, server: 0.0.0.0:8080
2018/10/09 17:05:50 [error] 29078#0: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:31):2: attempt to index global 'sock' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:31): in function <content_by_lua(nginx.conf:31):1>, udp client: 127.0.0.1, server: 0.0.0.0:8080
2018/10/09 17:11:30 [alert] 29315#0: *1 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8080", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/09 17:14:21 [error] 29360#0: *3 recv() failed (111: Connection refused) while proxying connection, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8081", bytes from/to client:15/0, bytes from/to upstream:0/15
2018/10/09 17:14:48 [alert] 29447#0: *1 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8080", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/09 17:14:50 [alert] 29447#0: *2 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8081", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/09 17:15:05 [alert] 29481#0: *1 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8080", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/09 17:15:07 [alert] 29481#0: *2 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8080", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/09 17:15:13 [alert] 29481#0: *3 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8080", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/09 17:17:05 [emerg] 29572#0: unknown log format "basic" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:31
2018/10/09 17:17:15 [emerg] 29598#0: log format is not specified in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:31
2018/10/09 17:17:27 [emerg] 29623#0: unknown log format "notice" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:31
2018/10/09 17:17:45 [emerg] 29652#0: log format is not specified in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:31
2018/10/09 17:18:39 [emerg] 29696#0: unknown log format "custom" in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:31
2018/10/09 17:19:06 [emerg] 29737#0: "log_format" directive is not allowed here in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:31
2018/10/09 17:19:26 [alert] 29784#0: *1 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8080", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/09 17:20:06 [alert] 29784#0: *2 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8080", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/09 17:20:40 [emerg] 30014#0: unknown "remote_user" variable
2018/10/09 17:20:57 [emerg] 30038#0: unknown "request" variable
2018/10/09 17:21:05 [emerg] 30057#0: unknown "body_bytes_sent" variable
2018/10/09 17:24:14 [alert] 30261#0: *1 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8080", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/09 17:25:37 [alert] 30373#0: *1 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8080", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/09 17:28:56 [emerg] 30523#0: unknown "realip_remote_addr" variable
2018/10/09 17:29:08 [alert] 30543#0: *1 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8080", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/09 17:29:16 [alert] 30543#0: *2 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8080", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/09 17:30:14 [crit] 30612#0: *1 bind(127.0.0.1:9999) failed (98: Address already in use) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8080", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/09 17:30:17 [crit] 30612#0: *2 bind(127.0.0.1:9999) failed (98: Address already in use) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8080", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/09 17:31:41 [alert] 30694#0: *1 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8080", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/10 08:15:54 [emerg] 5862#0: open() "/var/log/nginx/stream_udp.log" failed (13: Permission denied)
2018/10/10 08:34:31 [error] 6810#0: *1 failed to load inlined Lua code: content_by_lua(nginx.conf:80):2: unexpected symbol near '$', client: 127.0.0.1, server: localhost, request: "GET /echo_var HTTP/1.1", host: "localhost"
2018/10/10 08:35:51 [error] 6810#0: *2 failed to load inlined Lua code: content_by_lua(nginx.conf:80):2: unexpected symbol near '$', client: 127.0.0.1, server: localhost, request: "GET /echo_var HTTP/1.1", host: "localhost"
2018/10/10 08:54:40 [error] 7418#0: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:37):2: API disabled in the current context
stack traceback:
coroutine 0:
	[C]: in function 'say'
	content_by_lua(nginx.conf:37):2: in function <content_by_lua(nginx.conf:37):1>, udp client: 127.0.0.1, server: 0.0.0.0:81
2018/10/10 09:06:51 [error] 7728#0: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:43):2: API disabled in the current context
stack traceback:
coroutine 0:
	[C]: in function 'say'
	content_by_lua(nginx.conf:43):2: in function <content_by_lua(nginx.conf:43):1>, udp client: 127.0.0.1, server: 0.0.0.0:81
2018/10/10 09:07:06 [alert] 7770#0: *1 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8080", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/10 09:07:13 [alert] 7770#0: *2 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8080", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/10 09:12:16 [alert] 8020#0: *1 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: 127.0.0.1, server: 0.0.0.0:81, upstream: "127.0.0.1:8080", bytes from/to client:15/0, bytes from/to upstream:0/0
2018/10/10 09:22:20 [emerg] 8366#0: "access_by_lua_file" directive is not allowed here in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:36
2018/10/10 09:22:37 [error] 8421#0: *1 failed to load inlined Lua code: content_by_lua(nginx.conf:40):2: '=' expected near 'lua', udp client: 127.0.0.1, server: 0.0.0.0:81
2018/10/10 09:23:05 [error] 8421#0: *2 failed to load inlined Lua code: content_by_lua(nginx.conf:40):2: '=' expected near 'lua', udp client: 127.0.0.1, server: 0.0.0.0:81
2018/10/10 09:23:28 [error] 8421#0: *3 failed to load inlined Lua code: content_by_lua(nginx.conf:40):2: '=' expected near 'lua', udp client: 127.0.0.1, server: 0.0.0.0:81
2018/10/10 09:23:32 [error] 8500#0: *1 failed to load inlined Lua code: content_by_lua(nginx.conf:40):2: '=' expected near 'lua', udp client: 127.0.0.1, server: 0.0.0.0:81
2018/10/10 09:25:07 [emerg] 8592#0: "access_by_lua_file" directive is not allowed here in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:50
2018/10/10 09:25:38 [emerg] 8632#0: "location" directive is not allowed here in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:35
2018/10/10 09:26:49 [emerg] 8746#0: invalid number of arguments in "content_by_lua" directive in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:52
2018/10/17 16:43:46 [emerg] 15909#0: invalid number of arguments in "content_by_lua" directive in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:52
2018/10/17 16:44:14 [emerg] 15935#0: invalid number of arguments in "content_by_lua" directive in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:52
2018/10/17 16:45:10 [emerg] 15974#0: invalid number of arguments in "content_by_lua" directive in /home/dl/workspace/eotu_nginx/debug/nginx/conf/nginx.conf:51
